blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tweets.urls')),
]

tweets/urls.py
"""Defines URL patterns for tweets"""

from django.urls import path
from . import views

app_name = 'tweets'
urlpatterns = [
    # Home page:
    path('', views.index, name='index'),
    # Page that shows average posts
    path('posts/', views.posts, name='posts'),
    # Page that shows private posts
    path('more/', views.more, name='more'),
    # Page for reading comments under the average posts
    path('posts/<int:post_id>/', views.blog_com, name='blog_com'),
    # Page for reading comments under the private posts
    path('more/<int:post_id>/', views.priv_com, name='priv_com'),
    # Page for writing a new BlogPost
    path('new_post/', views.new_post, name='new_post'),
    # Page for writing a new PrivatePost
    path('new_prpost/', views.new_prpost, name='new_prpost'),
    # Page for writing a new BL-comment
    path('new_com/<int:post_id>/', views.new_com, name='new_com'),
    # Page for writing new PR-comments
    path('new_prcom/<int:post_id>/', views.new_prcom, name='new_prcom'),
    # Page that shows my diary
    path('my_diary/', views.my_diary, name='my_diary'),
    # Page for writing posts in my diary
    path('new_thought/', views.new_thought, name='new_thought'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),


]

tweets/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    """One post in the blog"""
    title = models.CharField(max_length=150)
    text = models.TextField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """String representation"""
        text_len = len(self.text[:])
        if text_len <= 200:
            return f'{self.text[:]}'
        else:
            return f'{self.text[:200]}...'


class PrivatePost(models.Model):
    """Post seen only by registered users"""
    title = models.CharField(max_length=150)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """String representation"""
        text_len = len(self.text[:])
        if text_len <= 200:
            return f'{self.text[:]}'
        else:
            return f'{self.text[:200]}...'


class BlogComments(models.Model):
    """A comment under the blog post"""
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        """String representation"""
        return self.text


class PrivateComments(models.Model):
    """A comment under the private post"""
    post = models.ForeignKey(PrivatePost, on_delete=models.CASCADE)
    text = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        """String representation"""
        return self.text

class SuperPrivatePost(models.Model):
    """A diary-type post for only one user"""
    title = models.CharField(max_length=300)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """String representation"""
        text_len = len(self.text[:])
        if text_len <= 200:
            return f'{self.text[:]}'
        else:
            return f'{self.text[:200]}...'

tweets/forms.py
from django import forms

from .models import BlogPost, PrivatePost, BlogComments, PrivateComments, SuperPrivatePost

class BlPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Write here your thoughts...'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}



class PrPostForm(forms.ModelForm):
    class Meta:
        model = PrivatePost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Don\'t be shy, characters\'re unlimited!'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class BlComForm(forms.ModelForm):
    class Meta:
        model = BlogComments
        fields = ['text']
        labels = {'text': 'Type...'}


class PrComForm(forms.ModelForm):
    class Meta:
        model = PrivateComments
        fields = ['text']
        labels = {'text': 'Type...'}


class SupPrPostForm(forms.ModelForm):
    class Meta:
        model = SuperPrivatePost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Dear Diary, ...'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

tweets/views.py
import http

from django.shortcuts import render, redirect
from .models import BlogPost, PrivatePost, SuperPrivatePost, User
from .forms import BlPostForm, PrPostForm, BlComForm, PrComForm, SupPrPostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.
def index(request):
    """The home page of the Blog"""
    return render(request, 'tweets/index.html')


def posts(request):
    """The page that shows all the blog's posts"""
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'tweets/posts.html', context)


@login_required
def more(request):
    """The page that shows private posts"""
    post = PrivatePost.objects.order_by('-date_added')
    context = {'post': post}
    return render(request, 'tweets/more.html', context)


def blog_com(request, post_id):
    """The page that shows comments under the post"""
    post = BlogPost.objects.get(id=post_id)
    comments = post.blogcomments_set.order_by('-date_added')
    context = {'post': post, 'comments': comments}
    return render(request, 'tweets/blog_com.html', context)


@login_required
def priv_com(request, post_id):
    """The page that shows comments under the private post"""
    post = PrivatePost.objects.get(id=post_id)
    comments = post.privatecomments_set.order_by('-date_added')
    context = {'post': post, 'comments': comments}
    return render(request, 'tweets/priv_com.html', context)


@login_required
def new_post(request):
    """Write a new post"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = BlPostForm()
    else:
        # POST data submitted; process data
        form = BlPostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('tweets:posts')

    context = {'form': form}
    return render(request, 'tweets/new_post.html', context)


@login_required
def new_prpost(request):
    """Write a new private post"""
    if request.method != 'POST':
        form = PrPostForm()
    else:
        form = PrPostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('tweets:more')

    context = {'form': form}
    return render(request, 'tweets/new_prpost.html', context)


@login_required
def new_com(request, post_id):
    """Write a new BlogComment"""
    post = BlogPost.objects.get(id=post_id)

    if request.method != 'POST':
        form = BlComForm()
    else:
        form = BlComForm(data=request.POST)
        if form.is_valid():
            new_comm = form.save(commit=False)
            new_comm.post = post
            new_comm.save()
            return redirect('tweets:blog_com', post_id=post_id)

    context = {'post': post, 'form': form}
    return render(request, 'tweets/new_com.html', context)


@login_required
def new_prcom(request, post_id):
    """Write a new PrivateComment"""
    post = PrivatePost.objects.get(id=post_id)

    if request.method != 'POST':
        form = PrComForm()
    else:
        form = PrComForm(data=request.POST)
        if form.is_valid():
            new_comm = form.save(commit=False)
            new_comm.post = post
            new_comm.save()
            return redirect('tweets:priv_com', post_id=post_id)

    context = {'post': post, 'form': form}
    return render(request, 'tweets/new_prcom.html', context)


@login_required
def my_diary(request):
    """Shows user's super private posts"""
    post = SuperPrivatePost.objects.filter(owner=request.user).order_by('-date_added')
    context = {'post': post}
    return render(request, 'tweets/my_diary.html', context)


@login_required
def new_thought(request):
    """Page for writing super private posts"""
    if request.method != 'POST':
        form = SupPrPostForm()
    else:
        form = SupPrPostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('tweets:my_diary')

    context = {'form': form}
    return render(request, 'tweets/new_thought.html', context)

tweets/templates/tweets/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>Kisik Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
    <a class="navbar-brand" href="{% url 'tweets:index' %}">Kisik Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tweets:posts' %}">
              Explore posts</a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tweets:my_diary' %}">My Diary</a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'tweets:more' %}">See more</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}</span>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Registration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

tweets/templates/tweets/blog_com.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
</head>
<body>

{% block page_header %}
  <h3>{{ post.title }}</h3>
  <h5>Comments:</h5>
  <a class="btn btn-lg btn-primary" href="{% url 'tweets:new_com' post.id %}" role="button">Add a comment</a>
{% endblock page_header %}

{% block content %}
  <p>
      <a href="{% url 'tweets:posts' %}">Back to posts</a>
  </p>
      {% for com in comments %}
        <div class="card mb-3">
          <h4 class="card-header">
              <small>{{ com.date_added|date:'M d, Y H:i' }}</small></h4>
          <div class="card-body">
            {{ com.text|linebreaks }}
          </div>
        </div>
      {% empty %}
        <p>No comments yet</p>
      {% endfor %}

{% endblock content %}
</body>
</html>

tweets/templates/tweets/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}}
</head>
<body>

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Welcome to the Kisik Blog!</h1>

    <p class="lead">Here you can share all your thoughts about any topic.
        Feel free to explore all the Blog.
        Log in or register to become the one of us - the Kisik!</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}" role="button">Log in &raquo;</a>
  </div>
{% endblock page_header %}

</body>
</html>

tweets/templates/tweets/more.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
</head>
<body>
{% block page_header %}
  <h1>Enjoy the Kisik Blog!</h1>
  <a class="btn btn-lg btn-primary" href="{% url 'tweets:new_prpost' %}" role="button">New big post</a>
{% endblock page_header %}

{% block content %}

      {% for post in post %}
        <div class="card mb-3">
          <h4 class="card-header">
            {{ post.title }}
            <small>{{ post.date_added|date:'M d, Y H:i' }}</small> -
            {{ post.owner }}
          </h4>
          <div class="card-body">
            {{ post.text|linebreaks }}
            <small><a href="{% url 'tweets:priv_com' post.id %}">See comments</a></small>
          </div>
        </div>
      {% empty %}
        <p>No posts added yet</p>
      {% endfor %}

{% endblock content %}
</body>
</html>

tweets/templates/tweets/my_diary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
</head>
<body>
{% block page_header %}
  <h1>Welcome to My Diary</h1>
  <h4>Here you can write your private thoughts. Nobody would ever read it except you.</h4>
  <a class="btn btn-lg btn-primary" href="{% url 'tweets:new_thought' %}" role="button">New diary post</a>
{% endblock page_header %}

{% block content %}

      {% for post in post %}
        <div class="card mb-3">
          <h4 class="card-header">
            {{ post.title }}
            <small>{{ post.date_added|date:'M d, Y H:i' }}</small>
          </h4>
          <div class="card-body">
            {{ post.text|linebreaks }}
          </div>
        </div>
      {% empty %}
        <p>No posts added yet</p>
      {% endfor %}

{% endblock content %}
</body>
</html>

tweets/templates/tweets/new_com.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
    {% load bootstrap4 %}
</head>
<body>

{% block page_header %}
  <h2>Add the comment:</h2>
  <a href="{% url 'tweets:blog_com' post.id %}">Back to comments</a>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'tweets:new_com' post.id %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Public</button>
      {% endbuttons %}
  </form>

{% endblock content %}
</body>
</html>

tweets/templates/tweets/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
    {% load bootstrap4 %}
</head>
<body>

{% block page_header %}
  <h2>Write the new post:</h2>
  <a href="{% url 'tweets:posts' %}">Back to posts</a>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'tweets:new_post' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Public</button>
      {% endbuttons %}
  </form>

{% endblock content %}
</body>
</html>

tweets/templates/tweets/new_prcom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   {% extends "tweets/base.html" %}
    {% load bootstrap4 %}
</head>
<body>

{% block page_header %}
  <h2>Add the comment:</h2>
  <a href="{% url 'tweets:priv_com' post.id %}">Back to comments</a>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'tweets:new_prcom' post.id %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Public</button>
      {% endbuttons %}
  </form>

{% endblock content %}
</body>
</html>

tweets/templates/tweets/new_prpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
    {% load bootstrap4 %}
</head>
<body>

{% block page_header %}
  <h2>Write the new post:</h2>
  <a href="{% url 'tweets:more' %}">Back to posts</a>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'tweets:new_prpost' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Public</button>
      {% endbuttons %}
  </form>

{% endblock content %}
</body>
</html>

tweets/templates/tweets/new_thought.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
    {% load bootstrap4 %}
</head>
<body>

{% block page_header %}
  <h2>Write your thoughts:</h2>
  <a href="{% url 'tweets:my_diary' %}">Back to My Diary</a>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'tweets:new_thought' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Save</button>
      {% endbuttons %}
  </form>

{% endblock content %}
</body>
</html>

tweets/templates/tweets/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
</head>
<body>

{% block page_header %}
  <h1>Posts:</h1>
  <a class="btn btn-lg btn-primary" href="{% url 'tweets:new_post' %}" role="button">New post</a>
{% endblock page_header %}

{% block content %}

      {% for post in posts %}
        <div class="card mb-3">
          <h4 class="card-header">
            {{ post.title }}
            <small>{{ post.date_added|date:'M d, Y H:i' }}</small> -
            {{ post.owner }}
          </h4>
          <div class="card-body">
            {{ post.text|linebreaks }}
            <small><a href="{% url 'tweets:blog_com' post.id %}">See comments</a></small>
          </div>
        </div>
      {% empty %}
        <p>No posts added yet</p>
      {% endfor %}

{% endblock content %}
</body>
</html>

tweets/templates/tweets/priv_com.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "tweets/base.html" %}
</head>
<body>
{% block page_header %}
  <h3>{{ post.title }}</h3>
  <h5>Comments:</h5>
  <a class="btn btn-lg btn-primary" href="{% url 'tweets:new_prcom' post.id %}" role="button">Add a comment</a>
{% endblock page_header %}

{% block content %}
  <p>
      <a href="{% url 'tweets:more' %}">Back to posts</a>
  </p>
      {% for com in comments %}
        <div class="card mb-3">
          <h4 class="card-header">
              <small>{{ com.date_added|date:'M d, Y H:i' }}</small></h4>
          <div class="card-body">
            {{ com.text|linebreaks }}
          </div>
        </div>
      {% empty %}
        <p>No comments yet</p>
      {% endfor %}

{% endblock content %}
</body>
</html>